spring:
  application:
    name: wms

  datasource:
    url: jdbc:h2:mem:wms;MODE=MYSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        ddl-auto: create-drop
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: dahae80912@gmail.com
    password: wbuo zdju vwbb zqoi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost # Redis ?? ???
      port: 6379      # Redis ?? ??

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.dahye.marketbackend
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true              # ?? ?? ??
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true               # Swagger UI ???? : ?? ?? => <http://localhost:8080/swagger-ui/index.html>
    path: /api-swagger.html         # Swagger UI ?? ?? ?? =>
    tags-sorter: alpha          # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha    # alpha: ??? ? ?? ??, method: HTTP Method ? ??

app:
  jwtSecret: 5TRwEzsnDlRL0mUTkKc2wHCy4auNF7AtLa9lE0HIo65v6QKHsJsDSNNeLilBEcnXxyiNCZN9zbEf6wtsUi1CbQ== #openssl rand -base64 64
